/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SW_Tx_UART_1.h"
#include "SW_Tx_UART_1_PVT.h"
#include "GREEN_LED.h"
#include "GREEN_LED_aliases.h"
#include "RED_LED.h"
#include "RED_LED_aliases.h"
#include "BLUE_LED.h"
#include "BLUE_LED_aliases.h"
#include "I2CM.h"
#include "I2CM_I2C.h"
#include "I2CM_PINS.h"
#include "I2CM_I2C_PVT.h"
#include "I2CM_PVT.h"
#include "I2CM_BOOT.h"
#include "SHD_LED_1.h"
#include "SHD_LED_1_aliases.h"
#include "SHD_LED_2.h"
#include "SHD_LED_2_aliases.h"
#include "TH_AL.h"
#include "TH_AL_aliases.h"
#include "TH_AH.h"
#include "TH_AH_aliases.h"
#include "MAG_SW_IN.h"
#include "MAG_SW_IN_aliases.h"
#include "RTC.h"
#include "RTC_PPS.h"
#include "PPS_ISR.h"
#include "I2CM_SCBCLK.h"
#include "I2CM_sda.h"
#include "I2CM_sda_aliases.h"
#include "I2CM_scl.h"
#include "I2CM_scl_aliases.h"
#include "I2CM_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

