#ifndef THREADS_SYNC_EVENTS_H
#define THREADS_SYNC_EVENTS_H

#define THREAD_SENSORS_RDY_EV               0x00000001
#define THREAD_CONSOLE_RDY_EV               0x00000002
#define THREAD_WIFI_RDY_EV                  0x00000004
#define THREAD_BLE_RDY_EV                   0x00000008

#define THREAD_WIFI_WLAN_SSID_EV            0x00000010
#define THREAD_WIFI_WLAN_SEC_EV             0x00000020
#define THREAD_WIFI_WLAN_PASSWD_EV          0x00000040

#define THREAD_WIFI_BOARD_SERIAL_EV         0x00000100


#define THREADS_ALL_RDY_EV                  ( THREAD_SENSORS_RDY_EV | THREAD_CONSOLE_RDY_EV | THREAD_WIFI_RDY_EV )
#define THREAD_WIFI_PROVISIONING_EV         ( THREAD_WIFI_WLAN_SSID_EV | THREAD_WIFI_WLAN_SEC_EV | THREAD_WIFI_WLAN_PASSWD_EV | THREAD_WIFI_BOARD_SERIAL_EV )

#endif  /* THREADS_SYNC_EVENTS_H */
