/* generated configuration header file - do not edit */
#ifndef BSP_IRQ_CFG_H_
#define BSP_IRQ_CFG_H_
#define BSP_IRQ_CFG_ADC0_SCAN_END (BSP_IRQ_DISABLED) /* ADC0 SCAN END: Disabled */
#define BSP_IRQ_CFG_ADC0_SCAN_END_B (BSP_IRQ_DISABLED) /* ADC0 SCAN END B: Disabled */
#define BSP_IRQ_CFG_ADC0_WINDOW_A (BSP_IRQ_DISABLED) /* ADC0 WINDOW A: Disabled */
#define BSP_IRQ_CFG_ADC0_WINDOW_B (BSP_IRQ_DISABLED) /* ADC0 WINDOW B: Disabled */
#define BSP_IRQ_CFG_ADC0_COMPARE_MATCH (BSP_IRQ_DISABLED) /* ADC0 COMPARE MATCH: Disabled */
#define BSP_IRQ_CFG_ADC0_COMPARE_MISMATCH (BSP_IRQ_DISABLED) /* ADC0 COMPARE MISMATCH: Disabled */
#define BSP_IRQ_CFG_ADC1_SCAN_END (BSP_IRQ_DISABLED) /* ADC1 SCAN END: Disabled */
#define BSP_IRQ_CFG_ADC1_SCAN_END_B (BSP_IRQ_DISABLED) /* ADC1 SCAN END B: Disabled */
#define BSP_IRQ_CFG_ADC1_WINDOW_A (BSP_IRQ_DISABLED) /* ADC1 WINDOW A: Disabled */
#define BSP_IRQ_CFG_ADC1_WINDOW_B (BSP_IRQ_DISABLED) /* ADC1 WINDOW B: Disabled */
#define BSP_IRQ_CFG_ADC1_COMPARE_MATCH (BSP_IRQ_DISABLED) /* ADC1 COMPARE MATCH: Disabled */
#define BSP_IRQ_CFG_ADC1_COMPARE_MISMATCH (BSP_IRQ_DISABLED) /* ADC1 COMPARE MISMATCH: Disabled */
#define BSP_IRQ_CFG_AGT0_INT (BSP_IRQ_DISABLED) /* AGT0 INT: Disabled */
#define BSP_IRQ_CFG_AGT0_COMPARE_A (BSP_IRQ_DISABLED) /* AGT0 COMPARE A: Disabled */
#define BSP_IRQ_CFG_AGT0_COMPARE_B (BSP_IRQ_DISABLED) /* AGT0 COMPARE B: Disabled */
#define BSP_IRQ_CFG_AGT1_INT (BSP_IRQ_DISABLED) /* AGT1 INT: Disabled */
#define BSP_IRQ_CFG_AGT1_COMPARE_A (BSP_IRQ_DISABLED) /* AGT1 COMPARE A: Disabled */
#define BSP_IRQ_CFG_AGT1_COMPARE_B (BSP_IRQ_DISABLED) /* AGT1 COMPARE B: Disabled */
#define BSP_IRQ_CFG_CAC_FREQUENCY_ERROR (BSP_IRQ_DISABLED) /* CAC FREQUENCY ERROR: Disabled */
#define BSP_IRQ_CFG_CAC_MEASUREMENT_END (BSP_IRQ_DISABLED) /* CAC MEASUREMENT END: Disabled */
#define BSP_IRQ_CFG_CAC_OVERFLOW (BSP_IRQ_DISABLED) /* CAC OVERFLOW: Disabled */
#define BSP_IRQ_CFG_CAN0_ERROR (BSP_IRQ_DISABLED) /* CAN0 ERROR: Disabled */
#define BSP_IRQ_CFG_CAN0_FIFO_RX (BSP_IRQ_DISABLED) /* CAN0 FIFO RX: Disabled */
#define BSP_IRQ_CFG_CAN0_FIFO_TX (BSP_IRQ_DISABLED) /* CAN0 FIFO TX: Disabled */
#define BSP_IRQ_CFG_CAN0_MAILBOX_RX (BSP_IRQ_DISABLED) /* CAN0 MAILBOX RX: Disabled */
#define BSP_IRQ_CFG_CAN0_MAILBOX_TX (BSP_IRQ_DISABLED) /* CAN0 MAILBOX TX: Disabled */
#define BSP_IRQ_CFG_CAN1_ERROR (BSP_IRQ_DISABLED) /* CAN1 ERROR: Disabled */
#define BSP_IRQ_CFG_CAN1_FIFO_RX (BSP_IRQ_DISABLED) /* CAN1 FIFO RX: Disabled */
#define BSP_IRQ_CFG_CAN1_FIFO_TX (BSP_IRQ_DISABLED) /* CAN1 FIFO TX: Disabled */
#define BSP_IRQ_CFG_CAN1_MAILBOX_RX (BSP_IRQ_DISABLED) /* CAN1 MAILBOX RX: Disabled */
#define BSP_IRQ_CFG_CAN1_MAILBOX_TX (BSP_IRQ_DISABLED) /* CAN1 MAILBOX TX: Disabled */
#define BSP_IRQ_CFG_CGC_MOSC_STOP (BSP_IRQ_DISABLED) /* CGC MOSC STOP: Disabled */
#define BSP_IRQ_CFG_COMP_HS_0 (BSP_IRQ_DISABLED) /* COMP HS 0: Disabled */
#define BSP_IRQ_CFG_COMP_HS_1 (BSP_IRQ_DISABLED) /* COMP HS 1: Disabled */
#define BSP_IRQ_CFG_COMP_HS_2 (BSP_IRQ_DISABLED) /* COMP HS 2: Disabled */
#define BSP_IRQ_CFG_COMP_HS_3 (BSP_IRQ_DISABLED) /* COMP HS 3: Disabled */
#define BSP_IRQ_CFG_COMP_HS_4 (BSP_IRQ_DISABLED) /* COMP HS 4: Disabled */
#define BSP_IRQ_CFG_COMP_HS_5 (BSP_IRQ_DISABLED) /* COMP HS 5: Disabled */
#define BSP_IRQ_CFG_CTSU_WRITE (BSP_IRQ_DISABLED) /* CTSU WRITE: Disabled */
#define BSP_IRQ_CFG_CTSU_READ (BSP_IRQ_DISABLED) /* CTSU READ: Disabled */
#define BSP_IRQ_CFG_CTSU_END (BSP_IRQ_DISABLED) /* CTSU END: Disabled */
#define BSP_IRQ_CFG_DMAC0_INT (BSP_IRQ_DISABLED) /* DMAC0 INT: Disabled */
#define BSP_IRQ_CFG_DMAC1_INT (BSP_IRQ_DISABLED) /* DMAC1 INT: Disabled */
#define BSP_IRQ_CFG_DMAC2_INT (BSP_IRQ_DISABLED) /* DMAC2 INT: Disabled */
#define BSP_IRQ_CFG_DMAC3_INT (BSP_IRQ_DISABLED) /* DMAC3 INT: Disabled */
#define BSP_IRQ_CFG_DMAC4_INT (BSP_IRQ_DISABLED) /* DMAC4 INT: Disabled */
#define BSP_IRQ_CFG_DMAC5_INT (BSP_IRQ_DISABLED) /* DMAC5 INT: Disabled */
#define BSP_IRQ_CFG_DMAC6_INT (BSP_IRQ_DISABLED) /* DMAC6 INT: Disabled */
#define BSP_IRQ_CFG_DMAC7_INT (BSP_IRQ_DISABLED) /* DMAC7 INT: Disabled */
#define BSP_IRQ_CFG_DOC_INT (BSP_IRQ_DISABLED) /* DOC INT: Disabled */
#define BSP_IRQ_CFG_DRW_INT (BSP_IRQ_DISABLED) /* DRW INT: Disabled */
#define BSP_IRQ_CFG_DTC_COMPLETE (BSP_IRQ_DISABLED) /* DTC COMPLETE: Disabled */
#define BSP_IRQ_CFG_DTC_END (BSP_IRQ_DISABLED) /* DTC END: Disabled */
#define BSP_IRQ_CFG_EDMAC0_EINT (BSP_IRQ_DISABLED) /* EDMAC0 EINT: Disabled */
#define BSP_IRQ_CFG_EDMAC1_EINT (BSP_IRQ_DISABLED) /* EDMAC1 EINT: Disabled */
#define BSP_IRQ_CFG_ELC_SOFTWARE_EVENT_0 (BSP_IRQ_DISABLED) /* ELC SOFTWARE EVENT 0: Disabled */
#define BSP_IRQ_CFG_ELC_SOFTWARE_EVENT_1 (BSP_IRQ_DISABLED) /* ELC SOFTWARE EVENT 1: Disabled */
#define BSP_IRQ_CFG_EPTPC_IPLS (BSP_IRQ_DISABLED) /* EPTPC IPLS: Disabled */
#define BSP_IRQ_CFG_EPTPC_MINT (BSP_IRQ_DISABLED) /* EPTPC MINT: Disabled */
#define BSP_IRQ_CFG_EPTPC_PINT (BSP_IRQ_DISABLED) /* EPTPC PINT: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER0_RISE (BSP_IRQ_DISABLED) /* EPTPC TIMER0 RISE: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER1_RISE (BSP_IRQ_DISABLED) /* EPTPC TIMER1 RISE: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER2_RISE (BSP_IRQ_DISABLED) /* EPTPC TIMER2 RISE: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER3_RISE (BSP_IRQ_DISABLED) /* EPTPC TIMER3 RISE: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER4_RISE (BSP_IRQ_DISABLED) /* EPTPC TIMER4 RISE: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER5_RISE (BSP_IRQ_DISABLED) /* EPTPC TIMER5 RISE: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER0_FALL (BSP_IRQ_DISABLED) /* EPTPC TIMER0 FALL: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER1_FALL (BSP_IRQ_DISABLED) /* EPTPC TIMER1 FALL: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER2_FALL (BSP_IRQ_DISABLED) /* EPTPC TIMER2 FALL: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER3_FALL (BSP_IRQ_DISABLED) /* EPTPC TIMER3 FALL: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER4_FALL (BSP_IRQ_DISABLED) /* EPTPC TIMER4 FALL: Disabled */
#define BSP_IRQ_CFG_EPTPC_TIMER5_FALL (BSP_IRQ_DISABLED) /* EPTPC TIMER5 FALL: Disabled */
#define BSP_IRQ_CFG_FCU_FIFERR (BSP_IRQ_DISABLED) /* FCU FIFERR: Disabled */
#define BSP_IRQ_CFG_FCU_FRDYI (BSP_IRQ_DISABLED) /* FCU FRDYI: Disabled */
#define BSP_IRQ_CFG_GLCDC_LINE_DETECT (BSP_IRQ_DISABLED) /* GLCDC LINE DETECT: Disabled */
#define BSP_IRQ_CFG_GLCDC_UNDERFLOW_1 (BSP_IRQ_DISABLED) /* GLCDC UNDERFLOW 1: Disabled */
#define BSP_IRQ_CFG_GLCDC_UNDERFLOW_2 (BSP_IRQ_DISABLED) /* GLCDC UNDERFLOW 2: Disabled */
#define BSP_IRQ_CFG_GPT0_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT0 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT0_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT0 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT0_COMPARE_C (BSP_IRQ_DISABLED) /* GPT0 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT0_COMPARE_D (BSP_IRQ_DISABLED) /* GPT0 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT0_COMPARE_E (BSP_IRQ_DISABLED) /* GPT0 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT0_COMPARE_F (BSP_IRQ_DISABLED) /* GPT0 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT0_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT0 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT0_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT0 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT0_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT0 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT0_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT0 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT1_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT1 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT1_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT1 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT1_COMPARE_C (BSP_IRQ_DISABLED) /* GPT1 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT1_COMPARE_D (BSP_IRQ_DISABLED) /* GPT1 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT1_COMPARE_E (BSP_IRQ_DISABLED) /* GPT1 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT1_COMPARE_F (BSP_IRQ_DISABLED) /* GPT1 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT1_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT1 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT1_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT1 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT1_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT1 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT1_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT1 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT2_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT2 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT2_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT2 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT2_COMPARE_C (BSP_IRQ_DISABLED) /* GPT2 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT2_COMPARE_D (BSP_IRQ_DISABLED) /* GPT2 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT2_COMPARE_E (BSP_IRQ_DISABLED) /* GPT2 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT2_COMPARE_F (BSP_IRQ_DISABLED) /* GPT2 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT2_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT2 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT2_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT2 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT2_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT2 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT2_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT2 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT3_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT3 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT3_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT3 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT3_COMPARE_C (BSP_IRQ_DISABLED) /* GPT3 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT3_COMPARE_D (BSP_IRQ_DISABLED) /* GPT3 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT3_COMPARE_E (BSP_IRQ_DISABLED) /* GPT3 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT3_COMPARE_F (BSP_IRQ_DISABLED) /* GPT3 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT3_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT3 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT3_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT3 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT3_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT3 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT3_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT3 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT4_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT4 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT4_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT4 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT4_COMPARE_C (BSP_IRQ_DISABLED) /* GPT4 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT4_COMPARE_D (BSP_IRQ_DISABLED) /* GPT4 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT4_COMPARE_E (BSP_IRQ_DISABLED) /* GPT4 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT4_COMPARE_F (BSP_IRQ_DISABLED) /* GPT4 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT4_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT4 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT4_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT4 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT4_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT4 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT4_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT4 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT5_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT5 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT5_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT5 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT5_COMPARE_C (BSP_IRQ_DISABLED) /* GPT5 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT5_COMPARE_D (BSP_IRQ_DISABLED) /* GPT5 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT5_COMPARE_E (BSP_IRQ_DISABLED) /* GPT5 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT5_COMPARE_F (BSP_IRQ_DISABLED) /* GPT5 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT5_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT5 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT5_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT5 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT5_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT5 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT5_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT5 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT6_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT6 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT6_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT6 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT6_COMPARE_C (BSP_IRQ_DISABLED) /* GPT6 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT6_COMPARE_D (BSP_IRQ_DISABLED) /* GPT6 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT6_COMPARE_E (BSP_IRQ_DISABLED) /* GPT6 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT6_COMPARE_F (BSP_IRQ_DISABLED) /* GPT6 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT6_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT6 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT6_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT6 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT6_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT6 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT6_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT6 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT7_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT7 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT7_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT7 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT7_COMPARE_C (BSP_IRQ_DISABLED) /* GPT7 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT7_COMPARE_D (BSP_IRQ_DISABLED) /* GPT7 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT7_COMPARE_E (BSP_IRQ_DISABLED) /* GPT7 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT7_COMPARE_F (BSP_IRQ_DISABLED) /* GPT7 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT7_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT7 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT7_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT7 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT7_AD_TRIG_A (BSP_IRQ_DISABLED) /* GPT7 AD TRIG A: Disabled */
#define BSP_IRQ_CFG_GPT7_AD_TRIG_B (BSP_IRQ_DISABLED) /* GPT7 AD TRIG B: Disabled */
#define BSP_IRQ_CFG_GPT8_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT8 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT8_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT8 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT8_COMPARE_C (BSP_IRQ_DISABLED) /* GPT8 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT8_COMPARE_D (BSP_IRQ_DISABLED) /* GPT8 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT8_COMPARE_E (BSP_IRQ_DISABLED) /* GPT8 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT8_COMPARE_F (BSP_IRQ_DISABLED) /* GPT8 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT8_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT8 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT8_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT8 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT9_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT9 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT9_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT9 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT9_COMPARE_C (BSP_IRQ_DISABLED) /* GPT9 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT9_COMPARE_D (BSP_IRQ_DISABLED) /* GPT9 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT9_COMPARE_E (BSP_IRQ_DISABLED) /* GPT9 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT9_COMPARE_F (BSP_IRQ_DISABLED) /* GPT9 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT9_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT9 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT9_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT9 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT10_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT10 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT10_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT10 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT10_COMPARE_C (BSP_IRQ_DISABLED) /* GPT10 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT10_COMPARE_D (BSP_IRQ_DISABLED) /* GPT10 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT10_COMPARE_E (BSP_IRQ_DISABLED) /* GPT10 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT10_COMPARE_F (BSP_IRQ_DISABLED) /* GPT10 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT10_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT10 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT10_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT10 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT11_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT11 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT11_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT11 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT11_COMPARE_C (BSP_IRQ_DISABLED) /* GPT11 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT11_COMPARE_D (BSP_IRQ_DISABLED) /* GPT11 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT11_COMPARE_E (BSP_IRQ_DISABLED) /* GPT11 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT11_COMPARE_F (BSP_IRQ_DISABLED) /* GPT11 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT11_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT11 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT11_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT11 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT12_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT12 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT12_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT12 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT12_COMPARE_C (BSP_IRQ_DISABLED) /* GPT12 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT12_COMPARE_D (BSP_IRQ_DISABLED) /* GPT12 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT12_COMPARE_E (BSP_IRQ_DISABLED) /* GPT12 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT12_COMPARE_F (BSP_IRQ_DISABLED) /* GPT12 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT12_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT12 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT12_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT12 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT13_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT13 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT13_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT13 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT13_COMPARE_C (BSP_IRQ_DISABLED) /* GPT13 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT13_COMPARE_D (BSP_IRQ_DISABLED) /* GPT13 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT13_COMPARE_E (BSP_IRQ_DISABLED) /* GPT13 COMPARE E: Disabled */
#define BSP_IRQ_CFG_GPT13_COMPARE_F (BSP_IRQ_DISABLED) /* GPT13 COMPARE F: Disabled */
#define BSP_IRQ_CFG_GPT13_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT13 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT13_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT13 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ0 (7) /* ICU IRQ0: Priority 7 */
#define BSP_IRQ_CFG_ICU_IRQ1 (BSP_IRQ_DISABLED) /* ICU IRQ1: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ2 (BSP_IRQ_DISABLED) /* ICU IRQ2: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ3 (BSP_IRQ_DISABLED) /* ICU IRQ3: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ4 (BSP_IRQ_DISABLED) /* ICU IRQ4: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ5 (BSP_IRQ_DISABLED) /* ICU IRQ5: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ6 (BSP_IRQ_DISABLED) /* ICU IRQ6: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ7 (BSP_IRQ_DISABLED) /* ICU IRQ7: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ8 (BSP_IRQ_DISABLED) /* ICU IRQ8: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ9 (7) /* ICU IRQ9: Priority 7 */
#define BSP_IRQ_CFG_ICU_IRQ10 (BSP_IRQ_DISABLED) /* ICU IRQ10: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ11 (BSP_IRQ_DISABLED) /* ICU IRQ11: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ12 (BSP_IRQ_DISABLED) /* ICU IRQ12: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ13 (BSP_IRQ_DISABLED) /* ICU IRQ13: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ14 (BSP_IRQ_DISABLED) /* ICU IRQ14: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ15 (BSP_IRQ_DISABLED) /* ICU IRQ15: Disabled */
#define BSP_IRQ_CFG_ICU_SNOOZE_CANCEL (BSP_IRQ_DISABLED) /* ICU SNOOZE CANCEL: Disabled */
#define BSP_IRQ_CFG_IIC0_RXI (11) /* IIC0 RXI: Priority 11 */
#define BSP_IRQ_CFG_IIC0_TXI (11) /* IIC0 TXI: Priority 11 */
#define BSP_IRQ_CFG_IIC0_TEI (11) /* IIC0 TEI: Priority 11 */
#define BSP_IRQ_CFG_IIC0_ERI (11) /* IIC0 ERI: Priority 11 */
#define BSP_IRQ_CFG_IIC0_WUI (BSP_IRQ_DISABLED) /* IIC0 WUI: Disabled */
#define BSP_IRQ_CFG_IIC1_RXI (11) /* IIC1 RXI: Priority 11 */
#define BSP_IRQ_CFG_IIC1_TXI (11) /* IIC1 TXI: Priority 11 */
#define BSP_IRQ_CFG_IIC1_TEI (11) /* IIC1 TEI: Priority 11 */
#define BSP_IRQ_CFG_IIC1_ERI (11) /* IIC1 ERI: Priority 11 */
#define BSP_IRQ_CFG_IIC2_RXI (BSP_IRQ_DISABLED) /* IIC2 RXI: Disabled */
#define BSP_IRQ_CFG_IIC2_TXI (BSP_IRQ_DISABLED) /* IIC2 TXI: Disabled */
#define BSP_IRQ_CFG_IIC2_TEI (BSP_IRQ_DISABLED) /* IIC2 TEI: Disabled */
#define BSP_IRQ_CFG_IIC2_ERI (BSP_IRQ_DISABLED) /* IIC2 ERI: Disabled */
#define BSP_IRQ_CFG_IOPORT_EVENT_1 (BSP_IRQ_DISABLED) /* IOPORT EVENT 1: Disabled */
#define BSP_IRQ_CFG_IOPORT_EVENT_2 (BSP_IRQ_DISABLED) /* IOPORT EVENT 2: Disabled */
#define BSP_IRQ_CFG_IOPORT_EVENT_3 (BSP_IRQ_DISABLED) /* IOPORT EVENT 3: Disabled */
#define BSP_IRQ_CFG_IOPORT_EVENT_4 (BSP_IRQ_DISABLED) /* IOPORT EVENT 4: Disabled */
#define BSP_IRQ_CFG_IWDT_UNDERFLOW (BSP_IRQ_DISABLED) /* IWDT UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_JPEG_JEDI (BSP_IRQ_DISABLED) /* JPEG JEDI: Disabled */
#define BSP_IRQ_CFG_JPEG_JDTI (BSP_IRQ_DISABLED) /* JPEG JDTI: Disabled */
#define BSP_IRQ_CFG_KEY_INT (BSP_IRQ_DISABLED) /* KEY INT: Disabled */
#define BSP_IRQ_CFG_LPM_SNOOZE_REQUEST (BSP_IRQ_DISABLED) /* LPM SNOOZE REQUEST: Disabled */
#define BSP_IRQ_CFG_LVD_LVD1 (BSP_IRQ_DISABLED) /* LVD LVD1: Disabled */
#define BSP_IRQ_CFG_LVD_LVD2 (BSP_IRQ_DISABLED) /* LVD LVD2: Disabled */
#define BSP_IRQ_CFG_OPS_UVW_EDGE (BSP_IRQ_DISABLED) /* OPS UVW EDGE: Disabled */
#define BSP_IRQ_CFG_PDC_RECEIVE_DATA_READY (BSP_IRQ_DISABLED) /* PDC RECEIVE DATA READY: Disabled */
#define BSP_IRQ_CFG_PDC_FRAME_END (BSP_IRQ_DISABLED) /* PDC FRAME END: Disabled */
#define BSP_IRQ_CFG_PDC_INT (BSP_IRQ_DISABLED) /* PDC INT: Disabled */
#define BSP_IRQ_CFG_POEG0_EVENT (BSP_IRQ_DISABLED) /* POEG0 EVENT: Disabled */
#define BSP_IRQ_CFG_POEG1_EVENT (BSP_IRQ_DISABLED) /* POEG1 EVENT: Disabled */
#define BSP_IRQ_CFG_POEG2_EVENT (BSP_IRQ_DISABLED) /* POEG2 EVENT: Disabled */
#define BSP_IRQ_CFG_POEG3_EVENT (BSP_IRQ_DISABLED) /* POEG3 EVENT: Disabled */
#define BSP_IRQ_CFG_QSPI_INT (12) /* QSPI INT: Priority 12 */
#define BSP_IRQ_CFG_RTC_ALARM (BSP_IRQ_DISABLED) /* RTC ALARM: Disabled */
#define BSP_IRQ_CFG_RTC_PERIOD (1) /* RTC PERIOD: Priority 1 */
#define BSP_IRQ_CFG_RTC_CARRY (BSP_IRQ_DISABLED) /* RTC CARRY: Disabled */
#define BSP_IRQ_CFG_SCE_PROC_BUSY (BSP_IRQ_DISABLED) /* SCE PROC BUSY: Disabled */
#define BSP_IRQ_CFG_SCE_ROMOK (BSP_IRQ_DISABLED) /* SCE ROMOK: Disabled */
#define BSP_IRQ_CFG_SCE_LONG_PLG (BSP_IRQ_DISABLED) /* SCE LONG PLG: Disabled */
#define BSP_IRQ_CFG_SCE_TEST_BUSY (BSP_IRQ_DISABLED) /* SCE TEST BUSY: Disabled */
#define BSP_IRQ_CFG_SCE_WRRDY_0 (BSP_IRQ_DISABLED) /* SCE WRRDY 0: Disabled */
#define BSP_IRQ_CFG_SCE_WRRDY_1 (BSP_IRQ_DISABLED) /* SCE WRRDY 1: Disabled */
#define BSP_IRQ_CFG_SCE_WRRDY_4 (BSP_IRQ_DISABLED) /* SCE WRRDY 4: Disabled */
#define BSP_IRQ_CFG_SCE_RDRDY_0 (BSP_IRQ_DISABLED) /* SCE RDRDY 0: Disabled */
#define BSP_IRQ_CFG_SCE_RDRDY_1 (BSP_IRQ_DISABLED) /* SCE RDRDY 1: Disabled */
#define BSP_IRQ_CFG_SCE_INTEGRATE_WRRDY (BSP_IRQ_DISABLED) /* SCE INTEGRATE WRRDY: Disabled */
#define BSP_IRQ_CFG_SCE_INTEGRATE_RDRDY (BSP_IRQ_DISABLED) /* SCE INTEGRATE RDRDY: Disabled */
#define BSP_IRQ_CFG_SCI0_RXI (BSP_IRQ_DISABLED) /* SCI0 RXI: Disabled */
#define BSP_IRQ_CFG_SCI0_TXI (BSP_IRQ_DISABLED) /* SCI0 TXI: Disabled */
#define BSP_IRQ_CFG_SCI0_TEI (BSP_IRQ_DISABLED) /* SCI0 TEI: Disabled */
#define BSP_IRQ_CFG_SCI0_ERI (BSP_IRQ_DISABLED) /* SCI0 ERI: Disabled */
#define BSP_IRQ_CFG_SCI0_AM (BSP_IRQ_DISABLED) /* SCI0 AM: Disabled */
#define BSP_IRQ_CFG_SCI0_RXI_OR_ERI (BSP_IRQ_DISABLED) /* SCI0 RXI OR ERI: Disabled */
#define BSP_IRQ_CFG_SCI1_RXI (BSP_IRQ_DISABLED) /* SCI1 RXI: Disabled */
#define BSP_IRQ_CFG_SCI1_TXI (BSP_IRQ_DISABLED) /* SCI1 TXI: Disabled */
#define BSP_IRQ_CFG_SCI1_TEI (BSP_IRQ_DISABLED) /* SCI1 TEI: Disabled */
#define BSP_IRQ_CFG_SCI1_ERI (BSP_IRQ_DISABLED) /* SCI1 ERI: Disabled */
#define BSP_IRQ_CFG_SCI1_AM (BSP_IRQ_DISABLED) /* SCI1 AM: Disabled */
#define BSP_IRQ_CFG_SCI2_RXI (BSP_IRQ_DISABLED) /* SCI2 RXI: Disabled */
#define BSP_IRQ_CFG_SCI2_TXI (BSP_IRQ_DISABLED) /* SCI2 TXI: Disabled */
#define BSP_IRQ_CFG_SCI2_TEI (BSP_IRQ_DISABLED) /* SCI2 TEI: Disabled */
#define BSP_IRQ_CFG_SCI2_ERI (BSP_IRQ_DISABLED) /* SCI2 ERI: Disabled */
#define BSP_IRQ_CFG_SCI2_AM (BSP_IRQ_DISABLED) /* SCI2 AM: Disabled */
#define BSP_IRQ_CFG_SCI3_RXI (BSP_IRQ_DISABLED) /* SCI3 RXI: Disabled */
#define BSP_IRQ_CFG_SCI3_TXI (BSP_IRQ_DISABLED) /* SCI3 TXI: Disabled */
#define BSP_IRQ_CFG_SCI3_TEI (BSP_IRQ_DISABLED) /* SCI3 TEI: Disabled */
#define BSP_IRQ_CFG_SCI3_ERI (BSP_IRQ_DISABLED) /* SCI3 ERI: Disabled */
#define BSP_IRQ_CFG_SCI3_AM (BSP_IRQ_DISABLED) /* SCI3 AM: Disabled */
#define BSP_IRQ_CFG_SCI4_RXI (BSP_IRQ_DISABLED) /* SCI4 RXI: Disabled */
#define BSP_IRQ_CFG_SCI4_TXI (BSP_IRQ_DISABLED) /* SCI4 TXI: Disabled */
#define BSP_IRQ_CFG_SCI4_TEI (BSP_IRQ_DISABLED) /* SCI4 TEI: Disabled */
#define BSP_IRQ_CFG_SCI4_ERI (BSP_IRQ_DISABLED) /* SCI4 ERI: Disabled */
#define BSP_IRQ_CFG_SCI4_AM (BSP_IRQ_DISABLED) /* SCI4 AM: Disabled */
#define BSP_IRQ_CFG_SCI5_RXI (BSP_IRQ_DISABLED) /* SCI5 RXI: Disabled */
#define BSP_IRQ_CFG_SCI5_TXI (BSP_IRQ_DISABLED) /* SCI5 TXI: Disabled */
#define BSP_IRQ_CFG_SCI5_TEI (BSP_IRQ_DISABLED) /* SCI5 TEI: Disabled */
#define BSP_IRQ_CFG_SCI5_ERI (BSP_IRQ_DISABLED) /* SCI5 ERI: Disabled */
#define BSP_IRQ_CFG_SCI5_AM (BSP_IRQ_DISABLED) /* SCI5 AM: Disabled */
#define BSP_IRQ_CFG_SCI6_RXI (BSP_IRQ_DISABLED) /* SCI6 RXI: Disabled */
#define BSP_IRQ_CFG_SCI6_TXI (BSP_IRQ_DISABLED) /* SCI6 TXI: Disabled */
#define BSP_IRQ_CFG_SCI6_TEI (BSP_IRQ_DISABLED) /* SCI6 TEI: Disabled */
#define BSP_IRQ_CFG_SCI6_ERI (BSP_IRQ_DISABLED) /* SCI6 ERI: Disabled */
#define BSP_IRQ_CFG_SCI6_AM (BSP_IRQ_DISABLED) /* SCI6 AM: Disabled */
#define BSP_IRQ_CFG_SCI7_RXI (BSP_IRQ_DISABLED) /* SCI7 RXI: Disabled */
#define BSP_IRQ_CFG_SCI7_TXI (BSP_IRQ_DISABLED) /* SCI7 TXI: Disabled */
#define BSP_IRQ_CFG_SCI7_TEI (BSP_IRQ_DISABLED) /* SCI7 TEI: Disabled */
#define BSP_IRQ_CFG_SCI7_ERI (BSP_IRQ_DISABLED) /* SCI7 ERI: Disabled */
#define BSP_IRQ_CFG_SCI7_AM (BSP_IRQ_DISABLED) /* SCI7 AM: Disabled */
#define BSP_IRQ_CFG_SCI8_RXI (BSP_IRQ_DISABLED) /* SCI8 RXI: Disabled */
#define BSP_IRQ_CFG_SCI8_TXI (BSP_IRQ_DISABLED) /* SCI8 TXI: Disabled */
#define BSP_IRQ_CFG_SCI8_TEI (BSP_IRQ_DISABLED) /* SCI8 TEI: Disabled */
#define BSP_IRQ_CFG_SCI8_ERI (BSP_IRQ_DISABLED) /* SCI8 ERI: Disabled */
#define BSP_IRQ_CFG_SCI8_AM (BSP_IRQ_DISABLED) /* SCI8 AM: Disabled */
#define BSP_IRQ_CFG_SCI9_RXI (BSP_IRQ_DISABLED) /* SCI9 RXI: Disabled */
#define BSP_IRQ_CFG_SCI9_TXI (BSP_IRQ_DISABLED) /* SCI9 TXI: Disabled */
#define BSP_IRQ_CFG_SCI9_TEI (BSP_IRQ_DISABLED) /* SCI9 TEI: Disabled */
#define BSP_IRQ_CFG_SCI9_ERI (BSP_IRQ_DISABLED) /* SCI9 ERI: Disabled */
#define BSP_IRQ_CFG_SCI9_AM (BSP_IRQ_DISABLED) /* SCI9 AM: Disabled */
#define BSP_IRQ_CFG_SDHIMMC0_ACCS (BSP_IRQ_DISABLED) /* SDHIMMC0 ACCS: Disabled */
#define BSP_IRQ_CFG_SDHIMMC0_SDIO (BSP_IRQ_DISABLED) /* SDHIMMC0 SDIO: Disabled */
#define BSP_IRQ_CFG_SDHIMMC0_CARD (BSP_IRQ_DISABLED) /* SDHIMMC0 CARD: Disabled */
#define BSP_IRQ_CFG_SDHIMMC0_DMA_REQ (BSP_IRQ_DISABLED) /* SDHIMMC0 DMA REQ: Disabled */
#define BSP_IRQ_CFG_SDHIMMC1_ACCS (BSP_IRQ_DISABLED) /* SDHIMMC1 ACCS: Disabled */
#define BSP_IRQ_CFG_SDHIMMC1_SDIO (BSP_IRQ_DISABLED) /* SDHIMMC1 SDIO: Disabled */
#define BSP_IRQ_CFG_SDHIMMC1_CARD (BSP_IRQ_DISABLED) /* SDHIMMC1 CARD: Disabled */
#define BSP_IRQ_CFG_SDHIMMC1_DMA_REQ (BSP_IRQ_DISABLED) /* SDHIMMC1 DMA REQ: Disabled */
#define BSP_IRQ_CFG_SPI0_RXI (9) /* SPI0 RXI: Priority 9 */
#define BSP_IRQ_CFG_SPI0_TXI (9) /* SPI0 TXI: Priority 9 */
#define BSP_IRQ_CFG_SPI0_IDLE (9) /* SPI0 IDLE: Priority 9 */
#define BSP_IRQ_CFG_SPI0_ERI (9) /* SPI0 ERI: Priority 9 */
#define BSP_IRQ_CFG_SPI0_TEI (BSP_IRQ_DISABLED) /* SPI0 TEI: Disabled */
#define BSP_IRQ_CFG_SPI1_RXI (BSP_IRQ_DISABLED) /* SPI1 RXI: Disabled */
#define BSP_IRQ_CFG_SPI1_TXI (BSP_IRQ_DISABLED) /* SPI1 TXI: Disabled */
#define BSP_IRQ_CFG_SPI1_IDLE (BSP_IRQ_DISABLED) /* SPI1 IDLE: Disabled */
#define BSP_IRQ_CFG_SPI1_ERI (BSP_IRQ_DISABLED) /* SPI1 ERI: Disabled */
#define BSP_IRQ_CFG_SPI1_TEI (BSP_IRQ_DISABLED) /* SPI1 TEI: Disabled */
#define BSP_IRQ_CFG_SRC_INPUT_FIFO_EMPTY (BSP_IRQ_DISABLED) /* SRC INPUT FIFO EMPTY: Disabled */
#define BSP_IRQ_CFG_SRC_OUTPUT_FIFO_FULL (BSP_IRQ_DISABLED) /* SRC OUTPUT FIFO FULL: Disabled */
#define BSP_IRQ_CFG_SRC_OUTPUT_FIFO_OVERFLOW (BSP_IRQ_DISABLED) /* SRC OUTPUT FIFO OVERFLOW: Disabled */
#define BSP_IRQ_CFG_SRC_OUTPUT_FIFO_UNDERFLOW (BSP_IRQ_DISABLED) /* SRC OUTPUT FIFO UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_SRC_CONVERSION_END (BSP_IRQ_DISABLED) /* SRC CONVERSION END: Disabled */
#define BSP_IRQ_CFG_SSI0_TXI (BSP_IRQ_DISABLED) /* SSI0 TXI: Disabled */
#define BSP_IRQ_CFG_SSI0_RXI (BSP_IRQ_DISABLED) /* SSI0 RXI: Disabled */
#define BSP_IRQ_CFG_SSI0_INT (BSP_IRQ_DISABLED) /* SSI0 INT: Disabled */
#define BSP_IRQ_CFG_SSI1_TXI_RXI (BSP_IRQ_DISABLED) /* SSI1 TXI RXI: Disabled */
#define BSP_IRQ_CFG_SSI1_INT (BSP_IRQ_DISABLED) /* SSI1 INT: Disabled */
#define BSP_IRQ_CFG_USBFS_FIFO_0 (BSP_IRQ_DISABLED) /* USBFS FIFO 0: Disabled */
#define BSP_IRQ_CFG_USBFS_FIFO_1 (BSP_IRQ_DISABLED) /* USBFS FIFO 1: Disabled */
#define BSP_IRQ_CFG_USBFS_INT (10) /* USBFS INT: Priority 10 */
#define BSP_IRQ_CFG_USBFS_RESUME (BSP_IRQ_DISABLED) /* USBFS RESUME: Disabled */
#define BSP_IRQ_CFG_USBHS_FIFO_0 (BSP_IRQ_DISABLED) /* USBHS FIFO 0: Disabled */
#define BSP_IRQ_CFG_USBHS_FIFO_1 (BSP_IRQ_DISABLED) /* USBHS FIFO 1: Disabled */
#define BSP_IRQ_CFG_USBHS_USB_INT_RESUME (10) /* USBHS USB INT RESUME: Priority 10 */
#define BSP_IRQ_CFG_WDT_UNDERFLOW (BSP_IRQ_DISABLED) /* WDT UNDERFLOW: Disabled */
#endif /* BSP_IRQ_CFG_H_ */
