/* generated configuration header file - do not edit */
#ifndef SF_EL_UX_COMMS_CFG_H_
#define SF_EL_UX_COMMS_CFG_H_
#define SF_EL_UX_COMMS_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define SF_EL_UX_COMMS_CFG_USB_MEMORY_SIZE_BYTES (65536)
#define SF_EL_UX_COMMS_CFG_BUFFER_MAX_LENGTH (500)
#endif /* SF_EL_UX_COMMS_CFG_H_ */
