/*
******************************************************************************
File:     tiny_printf.c
Info:     Generated by Atollic TrueSTUDIO 9.0.1   2018-06-13
Modified by:
	Andrew Gaylo - Arrow Electronics IoT Group - July 2018

Abstract: Atollic TrueSTUDIO Minimal iprintf/siprintf/fiprintf
          and puts/fputs.
          Provides aliased declarations for printf/sprintf/fprintf
          pointing to *iprintf variants.

          The argument contains a format string that may include
          conversion specifications. Each conversion specification
          is introduced by the character %, and ends with a
          conversion specifier.

          The following conversion specifiers are supported
          cdisuxX%

          Usage:
          c    character
          d,i  signed integer (-sign added, + sign not supported)
          s    character string
          u    unsigned integer as decimal
          X  unsigned integer as hexadecimal (uppercase letter)
		  X  unsigned integer as hexadecimal (lowercase letter)
          %    % is written (conversion specification is '%%')

          NULL strings are printed as (null)

          Note:
          Character padding IS supported.  Only digit based padding is
		  accepted, not spaces.
		  Examples:
			  int x=12;
			  printf("No pad: x%X\n",x);		-> xC
			  printf("1 pad : x%1X\n",x);		-> xC
			  printf("2 pad : x%2X\n",x);		-> x C
			  printf("3 pad : x%3X\n",x);		-> x  C
			  printf("01 pad: x%01X\n",x);		-> xC
			  printf("02 pad: x%02X\n",x);		-> x0C
			  printf("03 pad: x%03X\n",x);		-> x00C
			  printf("No pad: %d\n",x);			-> 12
			  printf("1 pad : %1d\n",x);		-> 12
			  printf("2 pad : %2d\n",x);		-> 12
			  printf("3 pad : %3d\n",x);		->  12
			  printf("01 pad: %01d\n",x);		-> 12
			  printf("02 pad: %02d\n",x);		-> 12
			  printf("03 pad: %03d\n",x);		-> 012

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

#define ISDIGIT(C)	((C)>='0' && (C)<='9')

/* Create aliases for *printf to integer variants *iprintf */
__attribute__ ((alias("iprintf"))) int printf(const char *fmt, ...);
__attribute__ ((alias("fiprintf"))) int fprintf(FILE* fp, const char *fmt, ...);
__attribute__ ((alias("siprintf"))) int sprintf(char* str, const char *fmt, ...);

/* External function prototypes (defined in syscalls.c) */
extern int _write(int fd, char *str, int len);

/* Private function prototypes */
void ts_itoa(char **buf, unsigned int d, int base, int hexcase, char pad_digit1, char pad_digit2);
int ts_formatstring(char *buf, const char *fmt, va_list va);
int ts_formatlength(const char *fmt, va_list va);

/* Private functions */


#define UPPER	1
#define LOWER	0

/**
**---------------------------------------------------------------------------
**  Abstract: Convert integer to ascii
**  Returns:  void
**---------------------------------------------------------------------------
*/
void ts_itoa(char **buf, unsigned int val, int base, int hexcase, char pad_digit1, char pad_digit2)
{
	int div = 1;
	char hexbase = 'A';
	int digits = 0;
#if 1
	if(pad_digit1>0)
	{
		// If only the first digit is set, then we are padding with space
		if(pad_digit2==0){ pad_digit2=pad_digit1; pad_digit1=' ';}
		pad_digit2 -= '0';
		// Calculate how many digits this will be
		for(digits=1;digits<pad_digit2;digits++) if(digits*base > val) break;	
		// If we need to pad, pad with the value
		if(digits<pad_digit2)  for(div=0;div<(pad_digit2-digits);div++) *((*buf)++)=pad_digit1;
	}
#endif
	if(base==16)
		if(hexcase==LOWER) hexbase = 'a';
	
	div = 1;
	while (val/div >= base)
		div *= base;

	while (div != 0)
	{
		int num = val/div;
		val = val%div;
		div /= base;
		if (num > 9)
			*((*buf)++) = (num-10) + hexbase;
		else
			*((*buf)++) = num + '0';
	}
}

/**
**---------------------------------------------------------------------------
**  Abstract: Writes arguments va to buffer buf according to format fmt
**  Returns:  Length of string
**---------------------------------------------------------------------------
*/
int ts_formatstring(char *buf, const char *fmt, va_list va)
{
	char *start_buf = buf;
	char pad_value_1;
	char pad_value_2;
	while(*fmt)
	{
		/* Character needs formating? */
		if (*fmt == '%')
		{
			fmt++;
			pad_value_1=0;
			pad_value_2=0;
			if(ISDIGIT(*fmt)){ pad_value_1=*fmt; fmt++; }
			if(ISDIGIT(*fmt)){ pad_value_2=*fmt; fmt++; }
			// Ignore additional format digits?
			while( ISDIGIT(*fmt) ) fmt++;
			
			switch (*(fmt))
			{
			  case 'c':
				*buf++ = va_arg(va, int);
				break;
			  case 'd':
			  case 'i':
				{
					signed int val = va_arg(va, signed int);
					if (val < 0)
					{
						val *= -1;
						*buf++ = '-';
					}
					ts_itoa(&buf, val, 10, 0, pad_value_1, pad_value_2);
				}
				break;
			  case 's':
				{
					char null[] = "(null)";
					char * arg;
					char * tmparg = va_arg(va, char *);
					if(tmparg==NULL) arg = null;
					else arg = tmparg;
					while (*arg)
					{
						*buf++ = *arg++;
					}
				}
				break;
			  case 'u':
					ts_itoa(&buf, va_arg(va, unsigned int), 10, 0, pad_value_1, pad_value_2);
				break;
			  case 'x':
					ts_itoa(&buf, va_arg(va, int), 16, LOWER, pad_value_1, pad_value_2);
				break;
			  case 'X':
					ts_itoa(&buf, va_arg(va, int), 16, UPPER, pad_value_1, pad_value_2);
				break;
			  case '%':
				  *buf++ = '%';
				  break;
			}
			fmt++;
		}
		/* Else just copy */
		else
		{
			*buf++ = *fmt++;
		}
	}
	*buf = 0;

	return (int)(buf - start_buf);
}


/**
**---------------------------------------------------------------------------
**  Abstract: Calculate maximum length of the resulting string from the
**            format string and va_list va
**  Returns:  Maximum length
**---------------------------------------------------------------------------
*/
int ts_formatlength(const char *fmt, va_list va)
{
	int length = 0;
	char pad_value;
	while (*fmt)
	{
		if (*fmt == '%')
		{
			++fmt;
			switch (*fmt)
			{
			  case 'c':
		  		  va_arg(va, int);
				  ++length;
				  break;
			  case 'd':
			  case 'i':
			  case 'u':
				  /* 32 bits integer is max 11 characters with minus sign */
				  length += 11;
				  va_arg(va, int);
				  break;
			  case 's':
			  	  {
			  		  char * str = va_arg(va, char *);
			  		  while (*str++)
			  			  ++length;
			  	  }
				  break;
			  case 'x':
			  case 'X':
				  /* 32 bits integer as hex is max 8 characters */
				  length += 8;
				  va_arg(va, unsigned int);
				  break;
			  default:
				  ++length;
				  break;
			}
		}
		else
		{
			++length;
		}
		++fmt;
	}
	return length;
}

/**
**===========================================================================
**  Abstract: Loads data from the given locations and writes them to the
**            given character string according to the format parameter.
**  Returns:  Number of bytes written
**===========================================================================
*/
int siprintf(char *buf, const char *fmt, ...)
{
	int length;
	va_list va;
	va_start(va, fmt);
	length = ts_formatstring(buf, fmt, va);
	va_end(va);
	return length;
}

/**
**===========================================================================
**  Abstract: Loads data from the given locations and writes them to the
**            given file stream according to the format parameter.
**  Returns:  Number of bytes written
**===========================================================================
*/
int fiprintf(FILE * stream, const char *fmt, ...)
{
	int length = 0;
	va_list va;
	va_start(va, fmt);
	length = ts_formatlength(fmt, va);
	va_end(va);
	{
		char buf[length];
		va_start(va, fmt);
		length = ts_formatstring(buf, fmt, va);
		length = _write(stream->_file, buf, length);
		va_end(va);
	}
	return length;
}

/**
**===========================================================================
**  Abstract: Loads data from the given locations and writes them to the
**            standard output according to the format parameter.
**  Returns:  Number of bytes written
**
**===========================================================================
*/
int iprintf(const char *fmt, ...)
{
	int length = 0;
	va_list va;
	va_start(va, fmt);
	length = ts_formatlength(fmt, va);
	va_end(va);
	{
		char buf[length];
		va_start(va, fmt);
		length = ts_formatstring(buf, fmt, va);
		length = _write(1, buf, length);
		va_end(va);
	}
	return length;
}

#if 0
/**
**===========================================================================
**  Abstract: fputs writes the string at s (but without the trailing null) to
**  the file or stream identified by fp.
**  Returns:  If successful, the result is 0; otherwise, the result is EOF.
**
**===========================================================================
*/
int fputs(const char *s, FILE *fp)
{
	int length = strlen(s);
	int wlen = 0;
	int res;

	wlen = _write((fp->_file), (char*)s, length);
	wlen += _write((fp->_file), "\n", 1);

	if (wlen == (length+1))
	{
		res = 0;
	}
	else
	{
		res = EOF;
	}

	return res;
}

/**
**===========================================================================
**  Abstract: puts writes the string at s (followed by a newline, instead of
**  the trailing null) to the standard output stream.
**  Returns:  If successful, the result is a nonnegative integer; otherwise,
**  the result is EOF.
**
**===========================================================================
*/
int puts(const char *s)
{
	int length = strlen(s);
	int numbytes = 0;
	int res;

	numbytes = _write(1, (char*)s, length);
	numbytes += _write(1, "\n", 1);

	if (numbytes == (length+1))
	{
		res = 0;
	}
	else
	{
		res = EOF;
	}

	return res;
}

/**
**===========================================================================
**  Abstract: Copy, starting from the memory location buf, count elements
**  (each of size size) into the file or stream identified by fp.
**  Returns:  Number of elements written
**
**===========================================================================
*/
size_t fwrite(const void * buf, size_t size, size_t count, FILE * fp)
{
	return (_write((fp->_file), (char*)buf, size * count) / size);
}
#endif
// EOF
